### ISSUE TITLE
config.options deprecation warning in Sidekiq 6.5.1

### ISSUE THREAD

**Issue by mattbrictson** [ixti/sidekiq-throttled-clone#5]
Using sidekiq-throttled with sidekiq 6.5.1 results in the following deprecation warnings being printed on startup:

```
WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["sidekiq-throttled-0.16.1/lib/sidekiq/throttled.rb:101:in `setup_strategy!'", "sidekiq-throttled-0.16.1/lib/sidekiq/throttled.rb:65:in `block in setup!'"]
WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["sidekiq-throttled-0.16.1/lib/sidekiq/throttled.rb:105:in `setup_strategy!'", "sidekiq-throttled-0.16.1/lib/sidekiq/throttled.rb:65:in `block in setup!'"]
```

Seems like `Sidekiq.options[:fetch]` should be replaced with `Sidekiq[:fetch]`.

https://github.com/ixti/sidekiq-throttled/blob/c9b2a49129791f9d5f4c13fbb966988a353974f9/lib/sidekiq/throttled.rb#L101

**Comment by ixti** [comment]
Thanks for the report!
